import type { Metadata } from "next";
import "./globals.css";
import classNames from "classnames";
import { Flare } from "@/components";
import { jost, parisienne } from "@/assets";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout(
    {children}: Readonly<{
        children: React.ReactNode;
    }>
) {
    return (
        <html lang="en">
            <body className={classNames("bg-background h-screen w-screen", jost.className)}>
                <div className={"w-full h-full bg-Noise opacity-10 absolute"}>
                </div>
                <div className={"w-6/12 aspect-video absolute top-1/2 left-1/2 transform" +
                    " -translate-x-1/2 -translate-y-1/2 opacity-10"}>
                    <Flare/>
                </div>
                {children}
                <span className={"text-white"}>test Jost</span><br/>
                <span className={classNames(parisienne.className, "text-white")}>test Parisienne</span>
            </body>
        </html>
    );
}
